linters:
  disable-all: true
  enable:
    - containedctx
    - errcheck
    - errname
    - exptostd
    - goconst
    - gocyclo
    - gofmt
    - goimports
    - gosec
    - gosimple
    - govet
    - iface
    - ineffassign
    - intrange
    - loggercheck
    - misspell
    - predeclared
    - recvcheck
    - revive
    - staticcheck
    - testpackage
    - thelper
    - unconvert
    - unparam
    - unused
    - whitespace
linters-settings:
  govet:
    enable:
      - nilness
  unused:
    go: "1.23"
