version: "2"
linters:
  default: none
  enable:
    - containedctx
    - errcheck
    - errname
    - exptostd
    - goconst
    - gocyclo
    - govet
    - iface
    - ineffassign
    - intrange
    - loggercheck
    - misspell
    - predeclared
    - recvcheck
    - revive
    - staticcheck
    - testpackage
    - thelper
    - unconvert
    - unparam
    - unused
    - whitespace
  settings:
    govet:
      enable:
        - nilness
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    paths:
      - third_party$
      - builtin$
      - examples$
formatters:
  enable:
    - gofmt
    - goimports
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
