// Code generated by "stringer -type=TypeCode -trimprefix=TypeCode"; DO NOT EDIT.

package defs

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[TypeCodeTitle-6200]
	_ = x[TypeCodeVideo-6201]
	_ = x[TypeCodeAudio-6202]
	_ = x[TypeCodeSubtitles-6203]
}

const _TypeCode_name = "TitleVideoAudioSubtitles"

var _TypeCode_index = [...]uint8{0, 5, 10, 15, 24}

func (i TypeCode) String() string {
	idx := int(i) - 6200
	if i < 6200 || idx >= len(_TypeCode_index)-1 {
		return "TypeCode(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _TypeCode_name[_TypeCode_index[idx]:_TypeCode_index[idx+1]]
}
